### ISSUE TITLE
drf-api: archive access exception - Unsupported lookup 'net_contains_or_equals'

### ISSUE THREAD

**Issue by vvidic** [esnet/esmond#45]
I get this strange exception while trying to access esmond running code from drf-api branch:

```
2016-01-18 10:13:19,114 [ERROR] /usr/lib/python2.7/dist-packages/django/core/handlers/base.py: Internal Server Error: /esmond/perfsonar/archive/
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python2.7/dist-packages/rest_framework/views.py", line 454, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/rest_framework/views.py", line 376, in initial
    self.perform_authentication(request)
  File "/usr/lib/python2.7/dist-packages/rest_framework/views.py", line 310, in perform_authentication
    request.user
  File "/usr/lib/python2.7/dist-packages/rest_framework/request.py", line 353, in __getattribute__
    return super(Request, self).__getattribute__(attr)
  File "/usr/lib/python2.7/dist-packages/rest_framework/request.py", line 193, in user
    self._authenticate()
  File "/usr/lib/python2.7/dist-packages/rest_framework/request.py", line 316, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/usr/lib/python2.7/dist-packages/esmond/api/perfsonar/api_v2.py", line 321, in authenticate
    userip = UserIpAddress.objects.filter(ip__net_contains_or_equals=remoteip).order_by("-ip")
  File "/usr/lib/python2.7/dist-packages/netfields/managers.py", line 83, in filter
    return super(NetManager, self).filter(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1310, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1338, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1209, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1100, in build_lookup
    lhs = self.try_transform(lhs, name, lookups)
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1118, in try_transform
    (name, lhs.output_field.__class__.__name__))
FieldError: Unsupported lookup 'net_contains_or_equals' for CidrAddressField or join on the field not 
```

There are also some warnings reported by manage.py that could be related to this:

```
System check identified some issues:

WARNINGS:
api.IfRef.ipAddr: (fields.W900) IPAddressField has been deprecated. Support for it (except in historical migrations) will be removed in Django 1.9.
        HINT: Use GenericIPAddressField instead.
api.LSPOpStatus.dstAddr: (fields.W900) IPAddressField has been deprecated. Support for it (except in historical migrations) will be removed in Django 1.9.
        HINT: Use GenericIPAddressField instead.
api.LSPOpStatus.srcAddr: (fields.W900) IPAddressField has been deprecated. Support for it (except in historical migrations) will be removed in Django 1.9.
        HINT: Use GenericIPAddressField instead.
```

**Comment by montegoode** [comment]
This looks like this is related to the django-netfields package. Have you refreshed the pip install -r requirements.txt to make sure you're getting the correct version?

@arlake228 - you fixed this issue before, it's just the net fields version, right?

**Comment by arlake228** [comment]
Yes, this should be fixed by 8aee639c89811b8f9cd4858aa1750d7ddc8509d0. As Monte suggests, try doing a fresh "pip install -r requirements.txt" to make sure it grabs the correct version

**Comment by tonin** [comment]
@vvidic Last week I had updated the debian/control file accordingly in the debian/wheezy branch, see https://github.com/esnet/esmond/commit/c3b49f05e43b691115c5b8521c6fe61f97b905ec You probably need to do the same for debian/jessie.

**Comment by vvidic** [comment]
I used a newer netfields version but I can give it one more try...

**Comment by arlake228** [comment]
Closing, branch where this was issue is gone.
